name: ci/cd workflow
 
on:
 push:
   branches:
     - 1.x
 
env:
  APACHE_TIKA_VERSION: 1.28.1

jobs:
 tests:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       php: [7.4]
 
   name: Test - PHP ${{ matrix.php }}
 
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
     - name: Cache PHP dependencies
       uses: actions/cache@v1
       with:
         path: vendor
         key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
 
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php }}
         extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
         coverage: none
 
     - name: Install dependencies
       run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
 
     - name: Download Apache Tika binaries
       run: ./scripts/download.sh
 
     - name: Start Apache Tika server
       run: ./scripts/spawn.sh
 
     - name: Execute tests
       run: vendor/bin/phpunit --verbose